### ISSUE TITLE
Tweenlite reference

### ISSUE THREAD

**Issue by bleepsandblops** [epranka/scrollmagic-plugin-gsap#6]
Hello,

Shouldn't this line https://github.com/epranka/scrollmagic-plugin-gsap/blob/master/index.js#L276 be `Tween` instead of `TweenLite`?

Cheers

**Comment by epranka** [comment]
Hi, probably yes. Source code is copied directly from https://scrollmagic.io/docs/plugins_animation.gsap.js.html

**Comment by jcrain** [comment]
I'm got a `ReferenceError: TweenLite is not defined` error. 

Updated to Tween as @bleepsandblops suggested and is working now

**Comment by jcrain** [comment]
I created a PR for this fix, https://github.com/epranka/scrollmagic-plugin-gsap/pull/7

**Comment by epranka** [comment]
@jcrain thanks, I merged it, but I can't update it in npm repository. I do it in the evening

**Comment by epranka** [comment]
@jcrain @bleepsandblops 
Updated in npm registry too. Thanks for contribution.

**Comment by jcrain** [comment]
@epranka Have you tried to use the indicators plugin with this setup? I haven't had any luck yet.
